version: "3"

services:
  web:
    build:
        context: ./web
        dockerfile: Dockerfile
    container_name: web
    environment:
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
    depends_on:
      - api
    ports:
      - "8380:8380"
    networks:
      - app-network
  api:
    build:
        context: ./api
        dockerfile: Dockerfile
    container_name: api
    environment:
      - deaths_filename=./data/CovidDeaths.csv
      - gdp_filename=./data/a4275215-339d-415e-a792-70f1f7215a5c_Data.csv
      - gdp2_filename=./data/GDP-by-Country-1999-2022.csv
    ports:
      - "1234:1234"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge